apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
  namespace: sock-shop
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br0",
      "isGateway": true,
      "ipMasq": true,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.20.0/24",
        "rangeStart": "192.168.20.100",
        "rangeEnd": "192.168.20.200",
        "gateway": "192.168.20.1"
      }
    }' 