apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: sock-shop
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "en0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.10.0/24",
        "rangeStart": "192.168.10.100",
        "rangeEnd": "192.168.10.200",
        "gateway": "192.168.10.1"
      }
    }' 