global:
  registry: docker.io

frontend:
  image:
    repository: ${DOCKER_USERNAME}/sockshop-frontend
    tag: ${IMAGE_TAG}
  resources:
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

catalogue:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

orders:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi

payment:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

shipping:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

user:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

carts:
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

# Database configurations
mongo:
  resources:
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 500Mi
  persistentVolume:
    enabled: true
    size: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

networkPolicies:
  enabled: true 