apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: sock-shop
spec:
  project: default
  source:
    repoURL: https://github.com/dhenob/kloia.git
    targetRevision: HEAD
    path: microservices-demo/deploy/kubernetes/helm-chart
    helm:
      valueFiles:
        - ../../../../helm-values/sock-shop/values.yaml
      parameters:
        - name: "frontend.image.tag"
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: "apps"
      kind: Deployment
      jsonPointers:
        - /spec/replicas 